# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-25 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabdetails',
            old_name='cabRegNo',
            new_name='cabNo',
        ),
        migrations.RemoveField(
            model_name='cabdetails',
            name='cabType',
        ),
        migrations.RemoveField(
            model_name='cabdetails',
            name='empName',
        ),
        migrations.RemoveField(
            model_name='cabdetails',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='cabdetails',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='cabdetails',
            name='rosterDate',
        ),
        migrations.RemoveField(
            model_name='cabdetails',
            name='tripTime',
        ),
        migrations.RemoveField(
            model_name='cabdetails',
            name='tripType',
        ),
    ]
